<?php
require "inc/settings.php";

/*! \mainpage UE4AM - persistent crossplatform online data interface for UE4
 *
 * \section intro_sec Introduction
 * For the default use, you don't need the Data Structures Documentation Tab.
 * But if you want to enhance UE4AM or work with this framework, feel free to constribute and share with
 * the community!
 *
 * This is a very early documentation, you are welcome to work with UE4AM and enhance it to your needs,
 * please share your work you did with UE4AM
 *
 * \section install_sec Installation
 *
 * \subsection step1 Step 1: Copy
 *
 * copy the files to your favourite hosting provider, providing mysql and php support
 *
 * You only need to edit settings.php in the /inc/ sub directory!
 * For easy use, all SQL tables and data will be automatically generated by UE4AM
 *
 * \subsection step2 Step 2: Migrate UE4AM Blueprints from demo project to your project
 *
 * migrate UE4AM Blueprints from demo project to your project
 * \subsection step3 Step 3 : Build
 *
 * build dedicated Server by using unrealbuildtool and prepare your game mode, game instance, 
 * 
 * to handle the data when you need it.
 *
 * Don't forget to register the App in UE4AM and create a security token!
 *
 * (c) 2014 by Tim Koepsel from Seven-Mountains (www.seven-mountains.eu)
 */
 
include "/inc/settings.php";
include "/inc/log.php";
include "/inc/dbhandler.php";
include "/inc/accounthandler.php";

/**
 * UE4AM (UE4 AccountManager)
 * 
 */
 /*! \brief UE4AM (UE4 AccountManager)
 * This is the main class  which handles all communication between database and clients 
 * 
 * You only need to call
 * Init();
 * AuthCMD();
 * 
 * to process and handle the whole thing
 */
class UE4AM
{
private $database;
private $log;
private $json;
private $apps;
private $accounts;

	/*! The Init Function is the first function you want to start after creating a new instance */  
	function Init()
	{
	global $log;
		// Init Log
		$this->log = new UE4AM_Log;
		
		// Init Database Connection
		$database = new UE4_DBHandler;
		$this->log->AddLog("UE4AM DB Handler loaded");
		
		// Init Json Handler
		$this->json = new UE4_JsonHandler;
		
		// Init App Handler
		$this->apps = new UE4_AppHandler;
		
		// Init Account System
		$this->accounts = new UE4_AccountHandler;
		$log->AddLog("UE4AM Account Handler loaded");
		
		$log->AddLog("UE4AM init complete");
		
		
	}
	
	/*! The AuthCMD checks if appid and token fit together and then process the command provided by received json array */  
	function AuthCMD()
	{
		// First we need to take our received array
		$received_jsonarray = $json->Receive();
		
		// And split it up a bit
		$appid = $received_jsonarray["appid"];
		$token = $received_jsonarray["token"];
		$command = $received_jsonarray["command"];
		
		if($app->Auth($appid, $token) == true)
		{
		
			/*! Add your custom commands here which can be later accessed by blueprint */
			/*! Each command takes its own case */
			
			/*! NOT READY YET - TODO: add functions for all needed commands, see UE4AM_AccountHandler or UE4AM_DBHandler */
			switch ($command) {
			
				/*! Following values need to be send by blueprint:
				string email, string username, string password */
				case "registeraccount":
				$accounts->Register($received_jsonarray["email"];,$received_jsonarray["username"];,$received_jsonarray["password"];);
				break; 
				
				/*! Following values need to be send by blueprint:
				string username, string password */
				case "login":
				$accounts->Login($received_jsonarray["username"];,$received_jsonarray["password"];);
				break;
				
				/*! Update the Account with new Data */
				case "updateaccount":
				
				break;
				
				/*! Sends a message through the message system, this is not live chat and person don't need to be online same time */
				case "sendmessage":
				
				break;
				
				/*! Saves the Character to the database */
				/*! This requires at least the characterid */
				case "savecharacter"
				
				break;
				
				/*! Sends a Ping to recognize user as connected user */
				case "sendping";
				$accounts->SendIPPing();
				break;
				
				/*! Logouts the User */
				case "logout":
				$accounts->Logout();
				break;
			}
			return true;
		} 
		else 
		{
		return false;
		}
		
	}
	
	/*! The Install function installs all necessary tables */  
	function Install()
	{
		if($this->IsInstalled()==false)
		{
		// First prepare the query
		
		/*! NOT READY YET - TODO: loop to read the /inc/UE4AM.sql  as $sql_install_data string */
		$sql_install_data = ' ';
		
		// Finally execute SQL
		$database->ExecSql($sql_install_data);
		}
	}
	
	/*! Checks if Database prerequisites are installed */  
	function IsInstalled()
	{
	
	/*! Check must be more detailed when the whole table structure is final in development */
		if(mysql_num_rows(mysql_query("SHOW TABLES LIKE 'ue4am'"))==1) 
		{
			return true; /*!< Returns true if prerequisites installed */  
		}
		else
		{
			return false; /*!< Returns false if prerequisites are not installed */  
		}
	}
	
	/*! This function should be called to send Data back to the Blueprint */
	/*! $data is a string containing the data encoded in json */
	
	function ExitWithData($data)
	{
		$json->
	}


}
 /*! \brief UE4AM Entry Point of the Script
 * This is the main entry point where we create UE4AM, and start the whole progress
 * 
 * On Script launch UE4AM inits and processes the command which has been received */  
$ue4am = new UE4_AccountManager;
$ue4am->Init();
$ue4am->AuthCMD();


?>