
<?php
/*! \mainpage UE4AM - persistent crossplatform online data interface for UE4
 *
 * \section intro_sec Introduction
 * For the default use, you don't need the Data Structures Documentation Tab.
 * But if you want to enhance UE4AM or work with this framework, feel free to constribute and share with
 * the community!
 *
 * This is a very early documentation, you are welcome to work with UE4AM and enhance it to your needs,
 * please share your work you did with UE4AM
 *
 * \section install_sec Installation
 *
 * \subsection step1 Step 1: Copy
 *
 * copy the files to your favourite hosting provider, providing mysql and php support
 *
 * You only need to edit settings.php in the /inc/ sub directory!
 * For easy use, all SQL tables and data will be automatically generated by UE4AM
 *
 * \subsection step2 Step 2: Migrate UE4AM Blueprints from demo project to your project
 *
 * migrate UE4AM Blueprints from demo project to your project
 * \subsection step3 Step 3 : Build
 *
 * build dedicated Server by using unrealbuildtool and prepare your game mode, game instance, 
 * 
 * to handle the data when you need it.
 *
 * Don't forget to register the App in UE4AM and create a security token!
 *
 * 
 */
 
include "/inc/settings.php";
include "/inc/log.php";
include "/inc/dbhandler.php";
include "/inc/accounthandler.php";

/**
 * UE4AM (UE4 AccountManager)
 * 
 */
 /*! \brief UE4AM (UE4 AccountManager)
 * This is the main class  which handles all communication between database and clients 
 * 
 * You only need to call
 * Init();
 * AuthCMD();
 * 
 * to process and handle the whole thing
 */
class UE4AM
{
private $database;
private $log;
private $json;
private $apps;
private $accounts;

	/*! The Init Function is the first function you want to start after creating a new instance */  
	function Init()
	{
	global $log;
		// Init Log
		$this->log = new UE4AM_Log;
		
		// Init Database Connection
		$database = new UE4_DBHandler;
		$this->log->AddLog("UE4AM DB Handler loaded");
		
		// Init Json Handler
		$this->json = new UE4_JsonHandler;
		
		// Init App Handler
		$this->apps = new UE4_AppHandler;
		
		// Init Account System
		$this->accounts = new UE4_AccountHandler;
		$log->AddLog("UE4AM Account Handler loaded");
		
		$log->AddLog("UE4AM init complete");
		
		
	}
	
	/*! The AuthCMD checks if appid and token fit together and then process the command provided by received json array */  
	function AuthCMD()
	{
		$received_jsonarray = $json->Receive();
		
		$appid = $json_array["appid"];
		$token = $json_array["token"];
		$command = $json_array["command"];
		
		if($app->Auth($appid, $token) == true)
		{
			switch ($command) {
				case "registeraccount":
				
				break; 
				
				case "login":
				
				break;
				
				case "updateaccount":
				
				break;
				
				case "sendmessage":
				
				break;
				
				case "logout":
				
				break;
			}
			return true;
		} 
		else 
		{
		return false;
		}
		
	}
	
	/*! The Install function installs all necessary tables */  
	function Install()
	{
	if($this->IsInstalled()==false)
	{
	
	}
	}
	
	/*! Checks if Database prerequisites are installed */  
	function IsInstalled()
	{
		if(mysql_num_rows(mysql_query("SHOW TABLES LIKE 'ue4am'"))==1) 
		{
			return true; /*!< Returns true if prerequisites installed */  
		}
		else
		{
			return false; /*!< Returns false if prerequisites are not installed */  
		}
	}



}

/*! On Script launch init UE4AM and process the command which has been received */  
$ue4am = new UE4_AccountManager;
$ue4am->Init();
$ue4am->AuthCMD();


?>